//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStat
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public System.Guid MatchId { get; set; }
        public int Kills { get; set; }
        public double AvgKills { get; set; }
        public int Damage { get; set; }
        public double AvgDamage { get; set; }
    }
}
